---
- name: Install Prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

#User + Key Setup
- name: Create a new user with sudo privilegas
  user:
    name: "{{ user }}"
    state: present
    groups: root
    append: true
    create_home: true
    shell: /bin/bash

- name: Set authorized key for remote user
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ local_key }}"
       
